// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyDMlwDSXf9M60Y-jmQtaPU0l7FUAS8VVhE',
    appId: '1:710654200487:web:f14ab8215dc6a64cf6e982',
    messagingSenderId: '710654200487',
    projectId: 'ard-blue-project',
    authDomain: 'ard-blue-project.firebaseapp.com',
    storageBucket: 'ard-blue-project.appspot.com',
    measurementId: 'G-M4V44HEPY0',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
    appId: '1:710654200487:android:42d186ba7c01ca39f6e982',
    messagingSenderId: '710654200487',
    projectId: 'ard-blue-project',
    storageBucket: 'ard-blue-project.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: '1:710654200487:ios:ef2130f93d70f8b9f6e982',
    messagingSenderId: '710654200487',
    projectId: 'ard-blue-project',
    storageBucket: 'ard-blue-project.appspot.com',
    iosBundleId: 'com.example.ardBlueWeb',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: '1:710654200487:ios:43344fff24de93dbf6e982',
    messagingSenderId: '710654200487',
    projectId: 'ard-blue-project',
    storageBucket: 'ard-blue-project.appspot.com',
    iosBundleId: 'com.example.ardBlueWeb.RunnerTests',
  );
}
